name: Continuous Integration

# Specifies that this workflow should run on push events to the repository and on pull requests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Run Tests
    runs-on: ubuntu-latest  # Specifies that the job should run on the latest version of Ubuntu

    strategy:
      matrix:
        node-version: [14.x, 16.x]  # Specifies the Node.js versions to test against

    steps:
    - name: Check out repository code
      uses: actions/checkout@v2  # Checks out your repository under $GITHUB_WORKSPACE, so your job can access it

    - name: Use Node.js ${{ matrix.node.version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}  # Sets up the specified Node.js version

    - name: Install dependencies
      run: npm install  # Installs dependencies defined in package.json

    - name: Run tests
      run: npm test  # Runs tests defined in package.json's "test" script

    - name: Build
      run: npm run build  # Builds your React app, optional if you just want to run tests
