name: Test Workflow

on: [push]

jobs:
  test_job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo "Hello, world!"
